apiVersion: v1
kind: Service
metadata:
  name: locust-master-svc
spec:
  selector:
    app: locust-master
  ports:
    - port: 8089
      name: web-ui
    - port: 5557
      name: worker-comm
    - port: 5558
      name: worker-comm-2